ALTER TABLE public.projects REPLICA IDENTITY FULL;
ALTER TABLE public.kanban_columns REPLICA IDENTITY FULL;
ALTER TABLE public.tasks REPLICA IDENTITY FULL;
ALTER TABLE public.task_checklists REPLICA IDENTITY FULL;
ALTER TABLE public.project_team REPLICA IDENTITY FULL;